---
name: module3_task0

"on":
  push:
  schedule:
    - cron: "5 6 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Make Help
        run: cd module3_task0 && make help
