---
name: module3_task2

"on":
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: installation Hugo with script
        run: |
          cd module3_task2 && ./setup.sh

      - name: validate makefile
        run: make help
          make build
          make lint
          make run
          make stop
          make clean
        working-directory: module3_task2

      - name: package
        run: cd module3_task2 && make package

      - name: tests
        run: cd module3_task2/ && make test

      - name: archive build
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module3_task2/awesome-website.zip
